// mario-react/src/components/Enemy/Enemy.jsx
import React, { useState, useEffect } from "react";

import enemyTexture from "/map/enemy.png";

const Enemy = ({
  initialPosition, //начальная позиция врага
  distance, //максимальное расстояние, на которое двигается враг вправо влево
  tileSize, //размер тайла
  playerPosition, //позиция игрока
  handleIsEnemyAndPlayerCollision, //коллизия с персом и врагом
}) => {
  //состояние которое хранит позицию врага
  const [enemyPosition, setEnemyPosition] = useState(initialPosition);
  //Состояние движение врага: 1 - вправо ; -1 - влево
  const [direction, setDirection] = useState(1);

  //хук для перемещения врага
  useEffect(() => {
    //Функция которая обновляет позицию врага, движется вправо или влево в зависимости от direction
    const moveEnemy = () => {
      setEnemyPosition((prevPosition) => {
        const newX = prevPosition.x + direction * tileSize * 0.3; //новая позиция врага по оси X

        if ( //Здесь проверяем движение врага
          //проверяем, не вышел ли он за правую или левую сторону его возможного движения
          //если новая позиция по оси X больше начальной на виличину distance, то идет в другую сторону
          newX > initialPosition.x + distance ||
          newX < initialPosition.x - distance
        ) {
          setDirection((prevDirection) => -prevDirection); //Тут меняется его направление
          return { ...prevPosition, x: newX };
        }
        return { ...prevPosition, x: newX };  //обновление позиции врага
      });
    };

    //функция которая обновляет движение игрока каждые 50 милисекунд
    const interval = setInterval(moveEnemy, 50); 

    return () => clearInterval(interval);
  }, [direction, enemyPosition, distance, tileSize]);

  useEffect(() => {
    //Проферка столкновения игрока с врагом
    //Каждый раз когда меняется позиция игрока, врага - проверяется 
    const checkCollisionWithPlayer = () => {
      const isCollising =
      //Проверяем если разница координат врага и перса меньше 80% от размера плитки по оси х и у
        Math.abs(enemyPosition.x - playerPosition.x) < tileSize * 0.8 &&
        Math.abs(enemyPosition.y - playerPosition.y) < tileSize * 0.8;
      //Если True, то вызываем функцию столкновения врага с персом
      if (isCollising) {
        handleIsEnemyAndPlayerCollision();
      }
    };

    //Вызывается непосредственно, чтобы сразу проверить столкновение кода происх изменения позиций
    //игрока или врага
    checkCollisionWithPlayer();
  }, [enemyPosition, playerPosition, tileSize]);

  return (
    <div //Элемент, представляющий собой врага в игре
      style={{
        position: "absolute",
        top: `${enemyPosition.y}px`,
        left: `${enemyPosition.x}px`,
        width: `${tileSize}px`,
        height: `${tileSize}px`,
        transition: ".3s",
        backgroundImage: `url(${enemyTexture})`,
      }}
    ></div>
  );
};

export default Enemy;

// mario-vue/src/components/Enemy.vue
<template>
  <!-- Шаблон отображения врага -->
  <div
    :style="{
      /* Абсолютное позиционирование элемента на карте */
      position: 'absolute',
      /* Установка позиции врага по оси Y */
      top: enemyPosition.y + 'px',
      /* Установка позиции врага по оси X */
      left: enemyPosition.x + 'px',
      /* Установка ширины элемента, равной размеру тайла */
      width: tileSize + 'px',
      /* Установка высоты элемента, равной размеру тайла */
      height: tileSize + 'px',
      /* Плавный переход для изменения позиции */
      transition: '.3s',
      /* Установка текстуры врага в качестве фона */
      backgroundImage: `url(${enemyTexture})`,
    }"
  ></div>
</template>

<script>
/* Импорт необходимых функций из Vue */
import { ref, reactive, onMounted, onUnmounted, watch } from "vue";
/* Импорт текстуры врага */
import enemyTexture from "/map/enemy.png";

export default {
  /* Декларация пропсов для передачи данных в компонент */
  props: {
    /* Начальная позиция врага (объект с координатами x и y) */
    initialPosition: Object,
    /* Расстояние, на которое враг может перемещаться в обе стороны от начальной позиции */
    distance: Number,
    /* Размер тайла, используемый для отображения врага */
    tileSize: Number,
    /* Текущая позиция игрока (объект с координатами x и y) */
    playerPosition: Object,
    /* Функция-обработчик для события столкновения врага и игрока */
    handleIsEnemyAndPlayerCollision: Function,
  },
  setup(props) {
    /* Создание реактивного объекта для позиции врага */
    const enemyPosition = reactive({ ...props.initialPosition });
    /* Направление движения врага: 1 (вперед) или -1 (назад) */
    const direction = ref(1);

    /* Функция для перемещения врага */
    const moveEnemy = () => {
      /* Новая координата X с учетом направления движения и шага */
      const newX = enemyPosition.x + direction.value * props.tileSize * 0.3;

      /* Проверяем, если враг достиг границ допустимого расстояния */
      if (
        newX > props.initialPosition.x + props.distance ||
        newX < props.initialPosition.x - props.distance
      ) {
        /* Меняем направление движения */
        direction.value *= -1;
      } else {
        /* Обновляем позицию врага */
        enemyPosition.x = newX;
      }
    };

    /* Функция для проверки столкновения врага с игроком */
    const checkCollisionWithPlayer = () => {
      /* Проверяем, достаточно ли близко враг и игрок */
      const isColliding =
        Math.abs(enemyPosition.x - props.playerPosition.x) <
          props.tileSize * 0.8 &&
        Math.abs(enemyPosition.y - props.playerPosition.y) <
          props.tileSize * 0.8;

      /* Если столкновение произошло, вызываем переданную функцию-обработчик */
      if (isColliding) {
        props.handleIsEnemyAndPlayerCollision();
      }
    };

    /* Переменная для хранения идентификатора интервала */
    let interval = null;

    /* Хук, срабатывающий при монтировании компонента */
    onMounted(() => {
      /* Устанавливаем интервал, чтобы враг двигался и проверял столкновения каждые 50 мс */
      interval = setInterval(() => {
        moveEnemy();
        checkCollisionWithPlayer();
      }, 50);
    });

    /* Хук, срабатывающий при размонтировании компонента */
    onUnmounted(() => {
      /* Очищаем интервал, чтобы предотвратить утечку памяти */
      if (interval) clearInterval(interval);
    });

    /* Наблюдаем за изменением позиции игрока */
    watch(props.playerPosition, (newPosition) => {
      /* Выводим обновленную позицию игрока в консоль */
      console.log("Updated player position:", newPosition);
    });

    /* Возвращаем данные и текстуру для использования в шаблоне */
    return {
      enemyPosition,
      tileSize: props.tileSize,
      enemyTexture,
    };
  },
};
</script>

<style scoped>
/* Локальные стили для компонента */
</style>
