// mario/src/components/MapRenderer/MapRenderer.jsx
import React, { useEffect, useState } from "react";
import Mario from "../Mario/Mario";

const BASE_URL = "http://localhost:5173/map/";

const MapRenderer = ({ mapFile }) => {
  const [mapData, setMapData] = useState(null);
  const [tilesets, setTilesets] = useState([]);
  const [collisionData, setCollisionData] = useState([]);
  const [ladderData, setLadderData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [initialPosition, setInitialPosition] = useState({ x: 0, y: 640 });
  const [lives, setLives] = useState(1);
  const [gameOver, setGameOver] = useState(false); // Флаг завершения игры
  const [timeElapsed, setTimeElapsed] = useState(0); // Время игры в секундах
  const [timerStarted, setTimerStarted] = useState(false); // Флаг для начала таймера

  // Координаты стартовой и финишной точки
  const start = { x: 0, y: 640 }; // Начальная точка
  const finish = { x: 1440, y: 63 }; // Конечная точка

  // Функция для проверки достижения финиша

  // Функция проверки попадания на слой с повреждением

  const drawLives = () => {
    const heartIcon = "❤️";
    return (
      <div
        style={{
          position: "absolute",
          top: "10px",
          left: "10px",
          fontSize: "24px",
        }}
      >
        {Array.from({ length: lives }).map((_, index) => (
          <span key={index} style={{ marginRight: "5px" }}>
            {heartIcon}
          </span>
        ))}
      </div>
    );
  };

  useEffect(() => {
    startGame();
  }, []);

  useEffect(() => {
    const loadMapData = async () => {
      const tileSize = 32; // Определите размер тайла (в пикселях)

      try {
        const response = await fetch(mapFile);
        if (!response.ok)
          throw new Error(`Failed to load map: ${response.statusText}`);
        const data = await response.json();

        setMapData(data);

        // Слой коллизий
        const collisionLayer = data.layers.find(
          (layer) => layer.name.toLowerCase() === "collision"
        );
        setCollisionData(collisionLayer?.objects || []);

        // Слой лестниц
        const ladderLayer = data.layers.find(
          (layer) => layer.name.toLowerCase() === "ladder"
        );

        if (ladderLayer && ladderLayer.type === "tilelayer") {
          const { data: layerData, width, height } = ladderLayer;
          const processedLadderData = [];

          for (let y = 0; y < height; y++) {
            for (let x = 0; x < width; x++) {
              const index = y * width + x;
              const tileId = layerData[index];

              if (tileId !== 0) {
                processedLadderData.push({
                  x: x * tileSize, // Координата X лестницы в пикселях
                  y: y * tileSize, // Координата Y лестницы в пикселях
                  width: tileSize, // Ширина тайла
                  height: tileSize, // Высота тайла
                });
              }
            }
          }

          setLadderData(processedLadderData);
        }
      } catch (error) {
        console.error("Error loading map:", error);
      } finally {
        setLoading(false);
      }
    };

    loadMapData();
  }, [mapFile]);

  useEffect(() => {
    if (!mapData) return;

    const loadTilesets = async () => {
      try {
        const tilesetPromises = mapData.tilesets.map(async (tileset) => {
          const response = await fetch(`${BASE_URL}${tileset.source}`);
          if (!response.ok)
            throw new Error(`Failed to load tileset: ${response.statusText}`);

          const xmlText = await response.text();
          const parser = new DOMParser();
          const xmlDoc = parser.parseFromString(xmlText, "application/xml");

          const imageElement = xmlDoc.querySelector("image");
          return {
            name: tileset.source,
            image: `${BASE_URL}${imageElement?.getAttribute("source")}`,
            tilewidth: parseInt(
              xmlDoc.documentElement.getAttribute("tilewidth")
            ),
            tileheight: parseInt(
              xmlDoc.documentElement.getAttribute("tileheight")
            ),
            columns: parseInt(xmlDoc.documentElement.getAttribute("columns")),
          };
        });

        const tilesetData = await Promise.all(tilesetPromises);
        setTilesets(tilesetData);
      } catch (error) {
        console.error("Error loading tilesets:", error);
      }
    };

    loadTilesets();
  }, [mapData]);

  useEffect(() => {
    if (lives <= 0 && !gameOver) {
      setGameOver(true);
    }
  }, [lives]);

  // Запуск таймера, если игра началась
  useEffect(() => {
    if (timerStarted) {
      const timer = setInterval(() => {
        setTimeElapsed((prev) => prev + 1); // Увеличиваем время каждую секунду
      }, 1000);

      return () => clearInterval(timer); // Очищаем таймер при завершении игры
    }
  }, [timerStarted]);

  const startGame = () => {
    setTimerStarted(true); // Запускаем таймер
  };

  if (loading || !mapData || tilesets.length === 0)
    return <div>Loading...</div>;

  const renderTileLayers = () => {
    return mapData.layers
      .filter((layer) => layer.data)
      .map((layer, layerIndex) =>
        layer.data.map((tileId, index) => {
          if (tileId === 0) return null;

          const tileset = tilesets.find(
            (_, i) =>
              tileId >= mapData.tilesets[i].firstgid &&
              (!mapData.tilesets[i + 1] ||
                tileId < mapData.tilesets[i + 1].firstgid)
          );
          if (!tileset) return null;

          const tileIndex =
            tileId - mapData.tilesets[tilesets.indexOf(tileset)].firstgid;
          const sourceX = (tileIndex % tileset.columns) * tileset.tilewidth;
          const sourceY =
            Math.floor(tileIndex / tileset.columns) * tileset.tileheight;

          const x = (index % layer.width) * mapData.tilewidth;
          const y = Math.floor(index / layer.width) * mapData.tileheight;

          return (
            <div
              key={`${layerIndex}-${index}`}
              style={{
                position: "absolute",
                left: x,
                top: y,
                width: mapData.tilewidth,
                height: mapData.tileheight,
                backgroundImage: `url(${tileset.image.replaceAll(" ", "%20")})`,
                backgroundPosition: `-${sourceX}px -${sourceY}px`,
                backgroundSize: `${tileset.tilewidth * tileset.columns}px`,
              }}
            />
          );
        })
      );
  };

  // Отображение сообщения о завершении игры
  if (gameOver) {
    return (
      <>
        <div>
          {lives <= 0
            ? "Game Over!"
            : "Вы победили!" + { timeElapsed } + " сек"}
        </div>
        <button onClick={() => window.location.reload()}>Еще раз?</button>
      </>
    );
  }

  return (
    <div
      style={{
        position: "relative",
        width: mapData.width * mapData.tilewidth,
        height: mapData.height * mapData.tileheight,
      }}
    >
      {renderTileLayers()}
      {drawLives()}
      <div
        style={{
          position: "absolute",
          top: "32px",
          right: "32px",
          zIndex: "9999",
        }}
      >
        Time: {timeElapsed} seconds
      </div>
      <Mario
        mapData={mapData}
        tileSize={mapData.tilewidth}
        collisionData={collisionData}
        ladderData={ladderData}
        lives={lives}
        setLives={setLives}
        initialPosition={initialPosition}
        setGameOver={setGameOver}
        finish={finish}
      />
    </div>
  );
};

export default MapRenderer;

// mario-vue/src/components/MapRenderer.vue
<template>
  <div
    v-if="gameOver"
    style="
      position: absolute;
      top: 100px;
      left: 50%;
      transform: translateX(-50%);
      text-align: center;
    "
  >
    <!-- Сообщение о завершении игры -->
    <div v-if="lives <= 0">Game Over!</div>
    <div v-else>Вы победили! {{ timeElapsed }} сек</div>
    <!-- Кнопка для перезагрузки игры -->
    <button
      @click="reloadGame"
      style="
        margin-top: 20px;
        padding: 10px 20px;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 5px;
      "
    >
      Еще раз?
    </button>
  </div>

  <!-- Игра показывается только если не окончена -->
  <div v-else>
    <div v-if="loading || !mapData || tilesets.length === 0">Loading...</div>

    <div
      v-else
      :style="{
        position: 'relative',
        width: mapData.width * mapData.tilewidth + 'px',
        height: mapData.height * mapData.tileheight + 'px',
      }"
    >
      <!-- Отрендерить все плитки карты -->
      <div
        v-for="(tile, index) in renderTileLayers()"
        :key="tile.key"
        :style="tile.style"
      ></div>

      <!-- Отображение сердечек -->
      <div
        v-if="lives > 0"
        :style="{
          position: 'absolute',
          top: '10px',
          left: '10px',
          fontSize: '24px',
        }"
      >
        <span
          v-for="(_, index) in Array(lives).fill(0)"
          :key="index"
          style="margin-right: 5px"
          >❤️</span
        >
      </div>

      <!-- Таймер -->
      <div
        :style="{
          position: 'absolute',
          top: '32px',
          right: '32px',
          zIndex: '9999',
          color: 'black',
          fontWeight: 'bold',
        }"
      >
        Time: {{ timeElapsed }} seconds
      </div>

      <!-- Враг -->
      <Enemy
        :initialPosition="{ x: 865, y: 323 }"
        :distance="100"
        :tileSize="32"
        :playerPosition="position"
        :handleIsEnemyAndPlayerCollision="handleIsEnemyAndPlayerCollision"
      />
      <Enemy
        :initialPosition="{ x: 768, y: 479.33 }"
        :distance="50"
        :tileSize="32"
        :playerPosition="position"
        :handleIsEnemyAndPlayerCollision="handleIsEnemyAndPlayerCollision"
      />

      <!-- Марио -->
      <Mario
        :map-data="mapData"
        :tile-size="mapData.tilewidth"
        :collision-data="collisionData"
        :ladder-data="ladderData"
        :lives="lives"
        :setLives="setLives"
        :setGameOver="setGameOver"
        :position="position"
        :initial-position="initialPosition"
        :finish="finish"
        @updatePosition="setPosition"
      />
    </div>
  </div>
</template>

<script>
import { ref, reactive, onMounted, watch } from "vue";
import Mario from "./Mario.vue";
import Enemy from "./Enemy.vue";

const BASE_URL = "http://localhost:5173/map/";

export default {
  name: "MapRenderer",
  components: {
    Mario,
    Enemy,
  },
  props: {
    mapFile: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    const mapData = ref(null);
    const tilesets = ref([]);
    const collisionData = ref([]);
    const ladderData = ref([]);
    const loading = ref(true);
    const initialPosition = reactive({ x: 31, y: 193 });
    const position = reactive({ x: initialPosition.x, y: initialPosition.y });

    const lives = ref(1);
    const gameOver = ref(false);
    const timeElapsed = ref(0);
    const timerStarted = ref(false);
    const start = reactive({ x: 0, y: 640 });
    const finish = reactive({ x: 1470, y: 737 });

    // Методы для обновления состояния
    const setLives = (newLives) => {
      lives.value = newLives;
    };

    const setGameOver = (isOver) => {
      gameOver.value = isOver;
    };

    const setPosition = (newPosition) => {
      position.x = newPosition.x;
      position.y = newPosition.y;
    };

    const loadMapData = async () => {
      const tileSize = 32;
      try {
        const response = await fetch(props.mapFile);
        if (!response.ok)
          throw new Error(`Failed to load map: ${response.statusText}`);
        const data = await response.json();

        mapData.value = data;

        const collisionLayer = data.layers.find(
          (layer) => layer.name.toLowerCase() === "collision"
        );
        collisionData.value = collisionLayer?.objects || [];

        const ladderLayer = data.layers.find(
          (layer) => layer.name.toLowerCase() === "ladder"
        );

        if (ladderLayer && ladderLayer.type === "tilelayer") {
          const { data: layerData, width, height } = ladderLayer;
          const processedLadderData = [];

          for (let y = 0; y < height; y++) {
            for (let x = 0; x < width; x++) {
              const index = y * width + x;
              const tileId = layerData[index];

              if (tileId !== 0) {
                processedLadderData.push({
                  x: x * tileSize,
                  y: y * tileSize,
                  width: tileSize,
                  height: tileSize,
                });
              }
            }
          }

          ladderData.value = processedLadderData;
        }
      } catch (error) {
        console.error("Error loading map:", error);
      } finally {
        loading.value = false;
      }
    };

    const loadTilesets = async () => {
      try {
        const tilesetPromises = mapData.value.tilesets.map(async (tileset) => {
          const response = await fetch(`${BASE_URL}${tileset.source}`);
          if (!response.ok)
            throw new Error(`Failed to load tileset: ${response.statusText}`);

          const xmlText = await response.text();
          const parser = new DOMParser();
          const xmlDoc = parser.parseFromString(xmlText, "application/xml");

          const imageElement = xmlDoc.querySelector("image");
          return {
            name: tileset.source,
            image: `${BASE_URL}${imageElement?.getAttribute("source")}`,
            tilewidth: parseInt(
              xmlDoc.documentElement.getAttribute("tilewidth")
            ),
            tileheight: parseInt(
              xmlDoc.documentElement.getAttribute("tileheight")
            ),
            columns: parseInt(xmlDoc.documentElement.getAttribute("columns")),
          };
        });

        tilesets.value = await Promise.all(tilesetPromises);
      } catch (error) {
        console.error("Error loading tilesets:", error);
      }
    };

    const renderTileLayers = () => {
      return mapData.value.layers
        .filter((layer) => layer.data)
        .flatMap((layer, layerIndex) =>
          layer.data.map((tileId, index) => {
            if (tileId === 0) return null;

            const tileset = tilesets.value.find(
              (_, i) =>
                tileId >= mapData.value.tilesets[i].firstgid &&
                (!mapData.value.tilesets[i + 1] ||
                  tileId < mapData.value.tilesets[i + 1].firstgid)
            );
            if (!tileset) return null;

            const tileIndex =
              tileId -
              mapData.value.tilesets[tilesets.value.indexOf(tileset)].firstgid;
            const sourceX = (tileIndex % tileset.columns) * tileset.tilewidth;
            const sourceY =
              Math.floor(tileIndex / tileset.columns) * tileset.tileheight;

            const x = (index % layer.width) * mapData.value.tilewidth;
            const y =
              Math.floor(index / layer.width) * mapData.value.tileheight;

            return {
              key: `${layerIndex}-${index}`,
              style: {
                position: "absolute",
                left: x + "px",
                top: y + "px",
                width: mapData.value.tilewidth + "px",
                height: mapData.value.tileheight + "px",
                backgroundImage: `url(${tileset.image.replaceAll(" ", "%20")})`,
                backgroundPosition: `-${sourceX}px -${sourceY}px`,
                backgroundSize: `${tileset.tilewidth * tileset.columns}px`,
              },
            };
          })
        )
        .filter(Boolean);
    };

    const handleIsEnemyAndPlayerCollision = () => {
      lives.value--;
      if (lives.value <= 0) {
        gameOver.value = true;
      }
    };

    const startGame = () => {
      timerStarted.value = true;
    };

    const reloadGame = () => {
      window.location.reload();
    };

    onMounted(() => {
      loadMapData();
      startGame();
    });

    watch(mapData, (newValue) => {
      if (newValue) {
        loadTilesets();
      }
    });

    watch(timerStarted, (started) => {
      if (started) {
        const timer = setInterval(() => {
          timeElapsed.value++;
        }, 1000);

        return () => clearInterval(timer);
      }
    });

    watch(position, (newPosition) => {
      console.log("Updated player position in MapRenderer:", newPosition);
    });

    return {
      mapData,
      tilesets,
      collisionData,
      ladderData,
      loading,
      initialPosition,
      position,
      lives,
      gameOver,
      timeElapsed,
      renderTileLayers,
      handleIsEnemyAndPlayerCollision,
      finish,
      setLives,
      setGameOver,
      setPosition,
      reloadGame,
    };
  },
};
</script>

<style scoped></style>
